export const TIMEFRAMES = ['1m', '5m', '15m', '30m', '1h', '1d', '1wk', '1mo']
export const REGIMES = ['trending_up', 'trending_down', 'ranging', 'high_volatility', 'low_volatility']
export const STOP_METHODS = ['fixed_pct', 'fixed_dollar', 'atr_multiple', 'prev_bar_low', 'n_bars_low', 'swing_low', 'fvg_low', 'sr_support', 'chandelier']
export const TARGET_METHODS = ['r_multiple', 'fixed_pct', 'atr_multiple', 'sr_resistance', 'swing_high', 'prev_day_high']
export const SIZING_METHODS = ['risk_pct', 'fixed_shares', 'fixed_dollar', 'fixed_pct_equity', 'atr_risk', 'kelly']
export const COOLDOWN_TRIGGERS = ['loss', 'win', 'stop_out', 'target_hit', 'any_exit', 'consecutive_loss']
export const FALLBACK_INDICATOR_KINDS = [
  'adx',
  'atr',
  'atr_14',
  'bb_lower',
  'bb_mid',
  'bb_upper',
  'bt_snipe',
  'chandelier',
  'dc_lower',
  'dc_mid',
  'dc_upper',
  'donchian',
  'donchian_high',
  'donchian_low',
  'earnings_blackout_active',
  'ema',
  'ema_9',
  'ema_21',
  'ema_55',
  'ema_200',
  'fractals',
  'hull_ma',
  'hull_ma_20',
  'hull_ma_50',
  'ibs',
  'ichimoku',
  'ichimoku_chikou',
  'ichimoku_kijun',
  'ichimoku_senkou_a',
  'ichimoku_senkou_b',
  'ichimoku_tenkan',
  'in_regular_session',
  'keltner',
  'macd',
  'macd_hist',
  'macd_signal',
  'market_day_type',
  'minus_di',
  'obv',
  'open_gap_pct',
  'opening_range_high',
  'opening_range_low',
  'pivot_points',
  'plus_di',
  'pp',
  'prev_day_close',
  'prev_day_high',
  'prev_day_low',
  'prev_month_close',
  'prev_month_high',
  'prev_month_low',
  'prev_week_close',
  'prev_week_high',
  'prev_week_low',
  'r1',
  'r2',
  'r3',
  'rsi',
  'rsi_14',
  'rsi_7',
  'rsi_3',
  'rsi_8',
  'rsi_2',
  's1',
  's2',
  's3',
  'sar',
  'sar_trend',
  'sma',
  'sma_20',
  'sma_50',
  'sma_200',
  'spread_zscore',
  'stoch_d',
  'stoch_k',
  'stochastic',
  'strat_num',
  'strat_dir',
  'swing_high',
  'swing_highs_lows',
  'swing_low',
  'volume_sma_20',
  'vwap',
  'vwap_session',
  'wma',
  'vwma',
  'zscore',
  'zscore_10',
  'zscore_20',
]

export const STOP_METHOD_LABELS: Record<string, string> = {
  fixed_pct: 'Fixed % below entry',
  fixed_dollar: 'Fixed $ amount',
  atr_multiple: 'ATR multiple',
  prev_bar_low: 'Previous bar low',
  n_bars_low: 'N-bar low',
  swing_low: 'Swing low',
  fvg_low: 'FVG low',
  sr_support: 'S/R support level',
  chandelier: 'Chandelier exit',
}
export const STOP_METHOD_HINTS: Record<string, string> = {
  fixed_pct: 'Stop = entry × (1 - stop%)',
  fixed_dollar: 'Exit when loss exceeds $ value',
  atr_multiple: 'Stop = entry - ATR(period) × multiplier',
  prev_bar_low: 'Stop at previous bar low',
  n_bars_low: 'Stop at lowest low over N bars',
  swing_low: 'Stop at most recent swing low',
  fvg_low: 'Stop at bottom of last fair value gap',
  sr_support: 'Stop just below nearest S/R support',
  chandelier: 'ATR-based trailing stop anchored to highest high',
}
export const SIZING_METHOD_LABELS: Record<string, string> = {
  risk_pct: 'Risk % of equity',
  fixed_shares: 'Fixed share count',
  fixed_dollar: 'Fixed dollar amount',
  fixed_pct_equity: 'Fixed % of equity',
  atr_risk: 'ATR-normalized risk',
  kelly: 'Kelly criterion',
}
export const SIZING_METHOD_HINTS: Record<string, string> = {
  risk_pct: 'Size = (equity × risk%) / stop_distance',
  fixed_shares: 'Always trade exactly N shares',
  fixed_dollar: 'Always trade a fixed dollar notional',
  fixed_pct_equity: 'Allocate a fixed % of current equity',
  atr_risk: 'Size via ATR-based dollar risk',
  kelly: 'Optimal Kelly fraction based on win rate and R',
}

export const DRAFT_STORAGE_KEY = 'strategy_creator_draft_v1'
